/** CATEGORY ACTION */
export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const FETCH_BY_ID_CATEGORY='FETCH_BY_ID_CATEGORY'
/** SELLER ACTION */
export const FETCH_PRODUCTS='FETCH_PRODUCTS'
export const CREATE_PRODUCT='CREATE_PRODUCT'
export const FETCH_POPULAR_SELLER='FETCH_POPULAR_SELLER'
export const FETCH_SELLER = 'FETCH_SELLER'
/** USER ACTION */
export const SIGN_IN = 'SIGN_IN'
export const SIGN_UP = 'SIGN_UP'
export const LOG_OUT = 'LOG_OUT'
export const USER_INFO = 'USER_INFO'
